import Header from "./Components/Header/page";
import BotaoFormulario from "./Components/BotaoFormulario/page";
import "./Global.css";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
       <Header />
       {children}
       <BotaoFormulario />
    </html>
  );
}
